<?php
/**
* SegHIS - Hospital Information System (DMC Deployment)
* Enhanced by Segworks Technologies Corporation
*/
/**
* Radiology Reports with Turn Around Time
* Update by Borj 2014-05-06
* edited by borj 2014-31-01
* turn-around-time
*/
/**
*Radiology Reports with Turn Around Time
*Update from Date Encoded to Date Official (Borj) 2014-07-24
*/

error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
require('./roots.php');

require_once($root_path."include/care_api_classes/class_hospital_admin.php");
require($root_path.'include/inc_environment_global.php');


require($root_path.'/modules/repgen/themes/dmc/dmc.php');
include_once($root_path.'include/care_api_classes/class_personell.php');

define(IPBMIPD_enc, 13);
define(IPBMOPD_enc, 14);

class Report_Radio extends DMCRepGen {
    var $from_date;
    var $to_date;
    var $request_status;
    var $pat_type;
    var $rpt_group; 
    var $radtech; 
    var $doctor_nr;
    var $is_alphabetical;
    var $encoder;
    var $status_report;

    function Report_Radio($fromdate,$todate,$request_status,$pat_type,$rpt_group, $radtech, $doctor_nr, $is_alphabetical, $status_report) {
        global $db, $HTTP_SESSION_VARS;

        $this->DMCRepGen("RADIOLOGICAL LOGBOOK", "L", array(215.9,330.2), $db, TRUE);
        #$this->DMCRepGen("RADIOLOGICAL LOGBOOK", "L", "Legal", $db, TRUE);


        $this->Caption = "RADIOLOGICAL LOGBOOK";
        $this->request_status = $request_status;
        $this->pat_type = $pat_type;
        $this->rpt_group = $rpt_group; 
        $this->radtech = $radtech; 
        $this->doctor_nr = $doctor_nr;
        $this->is_alphabetical = $is_alphabetical;
        $this->status_report = $status_report;
        
        $this->SetAutoPageBreak(FALSE);
        $this->LEFTMARGIN=0.1;
        $this->DEFAULT_TOPMARGIN = 1;

        $this->ColumnWidth = array(10,20,20,20,10,10,15,30,15,25,15,22,35,13,40,22);
        $this->Columns = 16;

        $this->TotalWidth = array_sum($this->ColumnWidth);

        $this->ColumnLabels = array(
                                        '',
                                        'HRN',
                                        'RID',
                                        'Patient',
                                        #'Birth Date',
                                        'Age',
                                        'Sex',
                                        'Type',
                                        'Service',
                                        'Section',
                                        'Date Served',
                                        #'Payment',
                                        'Served',
                                        'Date Official',
                                        'Rad Tech',
                                        'Result',
                                        'Reader',
                                        'Turn Around Time'
        );

        $this->RowHeight = 5;
        $this->TextHeight = 3.5;

        $this->Alignment = array('L','C','C','L','C','C','C','L','C','C','C','L','L','L','L');

        $this->PageOrientation = "L";

        if ($fromdate) $this->from_date=date("Y-m-d",strtotime($fromdate));
        if ($todate) $this->to_date=date("Y-m-d",strtotime($todate));

        $this->encoder = $HTTP_SESSION_VARS['sess_user_name'];

        $this->NoWrap = FALSE;

    }

    function Header() {

        $objInfo = new Hospital_Admin();
        
        if ($row = $objInfo->getAllHospitalInfo()) {
            $row['hosp_agency'] = strtoupper($row['hosp_agency']);
            $row['hosp_name']   = strtoupper($row['hosp_name']);
        }
        else {
            $row['hosp_country'] = "Republic of the Philippines";
            $row['hosp_agency']  = "DEPARTMENT OF HEALTH";
            $row['hosp_name']    = "DAVAO MEDICAL CENTER";
            $row['hosp_addr1']   = "JICA Bldg., JP Laurel Avenue, Davao City";
        }

        $this->LogoX = 94;
        $this->LogoY = 8;
        #$this->Image('../../gui/img/logos/dmc_logo.jpg',$this->LogoX,$this->LogoY,16,20);
        $this->SetFont("Arial","I","9");
        $this->Cell(0,4,$row['hosp_country'],$border2,1,'C');
        $this->Cell(0,4,$row['hosp_agency'],$border2,1,'C');
        $this->SetFont("Arial","B","10");
        $this->Cell(0,4,$row['hosp_name'],$border2,1,'C');
        $this->SetFont('Arial','B',11);
        $this->Ln(2);

        $this->SetFont('Arial','',8);
        $this->Cell(0,10,'Page '.$this->PageNo().' of {nb}. Generated by : '.$this->encoder.' '.date("m/d/Y h:iA"),0,0,'R');
        $this->Ln(2);
        $this->SetFont("Arial","B","12");
        $this->Cell(0,4,'RADIOLOGICAL LOGBOOK',$border2,1,'C');
        
        if (($this->from_date)==($this->to_date))
            $this->Cell(0,4,"For ".date("m/d/Y",strtotime($this->from_date)),$border2,1,'C');
        else
            $this->Cell(0,4,"From ".date("m/d/Y",strtotime($this->from_date))." to ".date("m/d/Y",strtotime($this->to_date)),$border2,1,'C');

        $this->Cell(0,4,'Number of Records : '.$this->_count,$border2,1,'L');
        
        $from_dt=strtotime($this->from_date);
        $to_dt=strtotime($this->to_date);
        
        /*if (!empty($this->from_date) && !empty($this->to_date))
        $this->Cell(0,5,
                sprintf('%s-%s',date("F j, Y",$from_dt),date("F j, Y",$to_dt)),
                $border2,1,'C');*/

        $this->Ln(1);

        parent::Header();

    }

    function BeforeData() {
        $this->FONTSIZE = 8;
        if ($this->colored) {
            $this->DrawColor = array(255,255,255);
        }
    }

    function FetchData() {
        $personell_obj=new Personell;
        
        if (empty($this->to_date)) 
            $end_date="NOW()";
        else $end_date=$this->to_date;
            
        if (empty($this->from_date)) 
            $start_date="NOW()";
        else
            $start_date=$this->from_date;
            
        if ($this->request_status){
            if ($this->request_status==1)
                $is_served = 1;
            else    
                $is_served = 0;
                
            $sql_request_status = " AND d.is_served= '".$is_served."'";
        }
        
        if ($this->pat_type==0)
            $enc_type = "";
        elseif ($this->pat_type==1)
            $enc_type = "AND encounter_type IN (1)";
        elseif ($this->pat_type==2)
            $enc_type = "AND encounter_type IN (3,4)";
        elseif ($this->pat_type==3)
            $enc_type = "AND encounter_type IN (2)";
        elseif ($this->pat_type==4)
            $enc_type = "AND encounter_type IS NULL";
        elseif ($this->pat_type==5)
            $enc_type = "AND (encounter_type IN (2) OR encounter_type IS NULL)";
        elseif ($this->pat_type==6)
            $enc_type = "AND encounter_type IN (1,3,4)";
        elseif ($this->pat_type==7)
            $enc_type = "AND encounter_type IN (".IPBMIPD_enc.")";
        elseif ($this->pat_type==8)
            $enc_type = "AND encounter_type IN (".IPBMOPD_enc.")";
        
       if ($this->rpt_group!=0)
            $group_cond = " AND g.department_nr='".$this->rpt_group."'";
        else
            $group_cond  = "";
        
        if ($this->radtech){
            $sql_radtech = " AND d.rad_tech= '".$this->radtech."'";
        }
        
        if ($this->doctor_nr){
            $sql_doctor_nr = "AND CONCAT(dr.con_doctor_nr,',', dr.sen_doctor_nr,',', dr.jun_doctor_nr) LIKE '%".$this->doctor_nr."%' ";
        }
        
        $sql_status = '';
        if ($this->status_report=='wo_result'){
            $sql_status = " AND f.batch_nr IS NULL ";    
        }elseif ($this->status_report=='w_result_initial'){
            $sql_status = " AND (f.batch_nr AND d.STATUS='pending') ";
        }elseif ($this->status_report=='w_result_official'){
            $sql_status = " AND (f.batch_nr AND d.STATUS='done') ";
        }
        
        $sql =  "SELECT h.pid,
                        fn_get_person_name(h.pid) AS patient_name, 
                        IF(fn_calculate_age(h.request_date,p.date_birth),fn_get_age(h.request_date,p.date_birth),age) AS age,
                        d.service_code,
                        s.NAME AS service_name,
                        dp.name_formal,
                        dp.name_short,
                        IF(d.is_served, 'Yes', 'Not Yet') AS is_served,
                        fn_get_personellname_lastfirstmi(d.rad_tech) AS radtech,
                        d.rad_tech,
                       CONCAT(h.request_date,' ', h.request_time) AS request_date,
                        rd.rid,
                        f.doctor_in_charge,
                        h.request_date,
                        d.service_date,
                        d.batch_nr,
                        CONCAT(dr.con_doctor_nr,',', dr.sen_doctor_nr,',', dr.jun_doctor_nr) AS doc_nr,
                        IF (d.served_date, d.served_date, IF(d.service_date,d.service_date,f.findings_date)) AS service_date,
                        e.encounter_type,
                        IF(h.is_cash,'Cash','Charge') AS iscash,
                        p.sex,
                        date_birth,
                        IF ((f.batch_nr && d.STATUS='done'),'Official',IF(f.batch_nr && d.STATUS='pending','Initial','None')) AS result,
                        IF (f.batch_nr && d.STATUS='pending','',TIMEDIFF(f.create_dt,d.served_date)) AS turn_around_time,
                        f.create_dt
                        -- IF (f.`modify_dt`='0000-00-00 00:00:00',TIMEDIFF(f.`create_dt`,d.`served_date`), TIMEDIFF(f.`modify_dt`,d.`served_date`)) AS turn_around_time


                FROM seg_radio_serv h
                INNER JOIN care_person p ON p.pid=h.pid
                INNER JOIN care_test_request_radio d ON d.refno=h.refno
                LEFT JOIN care_test_findings_radio f ON f.batch_nr=d.batch_nr
                LEFT JOIN care_test_findings_radio_doc_nr dr ON dr.batch_nr=d.batch_nr
                INNER JOIN seg_radio_services s ON s.service_code=d.service_code
                INNER JOIN seg_radio_service_groups g ON g.group_code=s.group_code
                INNER JOIN care_department dp ON dp.nr=g.department_nr
                INNER JOIN seg_radio_id rd ON rd.pid=h.pid
                LEFT JOIN care_encounter e ON e.encounter_nr=h.encounter_nr
                WHERE h.request_date BETWEEN ('".$start_date."') AND ('".$end_date."') 
                AND h.STATUS NOT IN ('deleted','hidden','inactive','void')
                AND d.STATUS NOT IN ('deleted','hidden','inactive','void')
                AND s.service_code NOT IN (SELECT service_code FROM seg_radio_services_excluded) AND g.fromdept='RD' 
                       $enc_type
                       $sql_request_status
                       $sql_radtech
                       $group_cond
                       $sql_doctor_nr
                       $sql_status
                       ";
           
        if ($this->is_alphabetical)
            $orderby = " ORDER BY p.name_last, p.name_first, p.name_middle, h.request_time";
        else
            $orderby = " ORDER BY h.request_date, h.request_time, p.name_last, p.name_first, p.name_middle";
        
        $sql .= $orderby;
        // echo $sql; die();
        #echo $create_dt;
        $result=$this->Conn->Execute($sql);
        $this->_count = $result->RecordCount();
        $this->Conn->SetFetchMode(ADODB_FETCH_ASSOC);
        if ($result) {
            $this->Data=array();
            $i=1;
            while ($row=$result->FetchRow()) {

                if($row["date_birth"]!='0000-00-00')
                    $bdate = date("m/d/Y",strtotime($row["date_birth"]));
                else
                    $bdate = "unknown";
                    
                if (stristr($row['age'],'years')){
                    $age = substr($row['age'],0,-5);
                    $age = floor($age).' y';
                }elseif (stristr($row['age'],'year')){
                    $age = substr($row['age'],0,-4);
                    $age = floor($age).' y';
                }elseif (stristr($row['age'],'months')){
                    $age = substr($row['age'],0,-6);
                    $age = floor($age).' m';
                }elseif (stristr($row['age'],'month')){
                    $age = substr($row['age'],0,-5);
                    $age = floor($age).' m';
                }elseif (stristr($row['age'],'days')){
                    $age = substr($row['age'],0,-4);

                    if ($age>30){
                        $age = $age/30;
                        $label = 'm';
                    }else
                        $label = 'd';

                    $age = floor($age).' '.$label;
                }elseif (stristr($row['age'],'day')){
                    $age = substr($row['age'],0,-3);
                    $age = floor($age).' d';
                }else{
                    $age = floor($row['age']).' y';
                }
                
                if ($row['encounter_type']==1){
                    $pat_type = "ERPx";
                }elseif ($row['encounter_type']==2){
                    $pat_type = 'OPDPx';
                }elseif (($row['encounter_type']==3)||($row['encounter_type']==4)){
                    $pat_type = 'InPx';
                }elseif (($row['encounter_type']==IPBMIPD_enc)){
                    $pat_type = 'InPx (IPBM)';
                }elseif (($row['encounter_type']==IPBMOPD_enc)){
                    $pat_type = 'OPDPx (IPBM)';
                }else{
                    $pat_type = 'WPx';
                }    
                
                if (stristr($row["service_date"],'{')){
                    $date_array = unserialize($row["service_date"]);
                    $row["service_date"] = $date_array[count($date_array)-1];    
                }    
                
                if(($row["service_date"]!='0000-00-00 00:00:00')&&($row["service_date"]!='0000-00-00')&&($row["service_date"]!=''))
                    $service_date = date("m/d/Y h:iA",strtotime($row["service_date"]));
                else
                    $service_date = "";
                    
                    $docs =  $row['doc_nr'];
                    $doctor_final2 = '';
                    $nr = explode(',',$docs);
                    foreach($nr as $key => $value){
                        if($value!=''){
                            $row_pr=$personell_obj->get_Person_name($value);
                            $dr_name = mb_strtoupper($row_pr['dr_name']).", ".$row_pr['drtitle'];
                            $pos =  mb_strtoupper(trim($row_pr['job_position']));
                            $doctor_final2 .= $dr_name."\n".$pos."\n";
                        }
                    }    
             
                #$doctor = mb_strtoupper($row['radtech']);
                $doctors_array = unserialize($row['doctor_in_charge']);
                #print_r($doctors_array);
                $doctor_final = $doctors_array[count($doctors_array)-1];
                if(!is_array($doctor_final) && $doctor_final != ''){
                   $doctor = mb_strtoupper(mb_convert_encoding($doctor_final, "ISO-8859-1", 'UTF-8')); 
                }else{
                    $doctor = mb_strtoupper(mb_convert_encoding($doctor_final2 , "ISO-8859-1", 'UTF-8')); 
                }

                /*if(($row["create_dt"]!='0000-00-00 00:00:00')&&($row["create_dt"]!='0000-00-00')&&($row["create_dt"]!='')){
                    $create_dt = date("m/d/Y h:iA",strtotime($row["create_dt"]));
                }else{
                    $create_dt = "";
                }*/

                 $create_dt = ($row["create_dt"] == NULL ? '' : date('m/d/Y h:i A',strtotime($row["create_dt"])));

                
                $this->Data[]=array(
                    $i,
                    $row['pid'],
                    $row['rid'],
                    mb_strtoupper(trim($row['patient_name'])),
                    #$bdate,
                    $age,
                    mb_strtoupper($row['sex']),
                    $pat_type,
                    $row['service_name'],
                    $row['name_short'],
                    $service_date,
                    #date("m/d/Y h:iA",strtotime($row['request_date'])),
                    #$row['iscash'],
                    $row['is_served'],
                    #$row['create_dt'],
                    $create_dt,
                    mb_strtoupper($row['radtech']),
                    $row['result'],
                    $doctor,
                    $row['turn_around_time'] 
                );

                $i++;
            }

        }
        else
            echo $this->Conn->ErrorMsg();
    }
}

$rep = new Report_Radio($_GET['fromdate'],$_GET['todate'],$_GET['request_status'],$_GET['pat_type'],$_GET['rpt_group'], $_GET['radtech'], $_GET['doctor_nr'],$_GET['is_alphabetical'],$_GET['status_report']);
$rep->AliasNbPages();
$rep->FetchData();
ini_set('memory_limit', '2048M'); 
$rep->Report();
?>