<?php
//Created by EJ 1/7/2015
//Jasper Report for List of Served Laboratory Services with Charge Type: NSC-M
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
require_once('roots.php');
require_once($root_path . 'include/inc_jasperReporting.php');
require_once($root_path . 'include/inc_environment_global.php');
include_once($root_path . 'include/care_api_classes/class_personell.php');
require_once($root_path.'include/care_api_classes/class_hospital_admin.php');
require_once($root_path.'include/care_api_classes/class_labservices_transaction.php');
$objLab = new SegLab();
$objInfo = new Hospital_Admin();
$pers_obj = new Personell;

function getHeaderLogo() {
	$top_dir = 'modules';
	$baseurl = sprintf(
		"%s://%s%s",
		isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off' ? 'https' : 'http',
		$_SERVER['SERVER_ADDR'],
		substr(dirname($_SERVER["REQUEST_URI"]), 0, strpos($_SERVER["REQUEST_URI"], $top_dir))
		);
	$params = array();
	$data[0] = array();
	return $baseurl."gui/img/logos/dmc_logo.jpg";
}

$baseDir = dirname(dirname(dirname(__FILE__))).'/';

if ($row = $objInfo->getAllHospitalInfo()) {
	$hosp_country = $row['hosp_country'];
	$hosp_agency = strtoupper($row['hosp_agency']);
	$hosp_name  = strtoupper($row['hosp_name']);
	$hosp_addr1 = $row['hosp_addr1'];
}
else {
	$hosp_country = "Republic of the Philippines";
	$hosp_agency  = "DEPARTMENT OF HEALTH";
	$hosp_name    = "SOUTHERN PHILIPPINES MEDICAL CENTER";
	$hosp_addr1   = "JICA Bldg., JP Laurel Avenue, Davao City";
}


$fromdate = $_GET['fromdate'];
$todate = $_GET['todate'];
$charge_type = $_GET['charge_type'];
$generator = $_GET['generator'];

$charge_type_name = $db->GetOne("SELECT charge_name FROM seg_type_charge WHERE id = '$charge_type'");

// $personell_name = 'LYDIA M. BUNO, RMT';
// $personell_position = 'Chief Medical Technologist';

$sig_info = $pers_obj->get_Signatory('NSCM');

if ($sig_info['title']) {
  $personell_name = mb_strtoupper($sig_info['name']).','.mb_strtoupper($sig_info['title']).'';
}
else {
  $personell_name = mb_strtoupper($sig_info['name']);
}

$params = array(
	'hosp_country' 	=> $hosp_country,
	'hosp_agency' 	=> $hosp_agency,
	'hosp_name' 	=> $hosp_name,
	'spmc_logo' 	=> $baseDir . "gui/img/logos/dmc_logo.jpg",
	'fromdate' 		=> date('m/d/Y' , strtotime($fromdate)),
	'todate' 		=> date('m/d/Y' , strtotime($todate)),
	'charge_type' 	=> $charge_type_name,
	'generator' 	=> 'Generated by '.$generator.' on '.date('m/d/Y H:i A'),
	'personell_name' => $personell_name,
	/*'personell_position' => $personell_position,*/
	'personell_position' => mb_strtoupper($sig_info['signatory_title']),
);

$from_date = date('Y-m-d', strtotime($fromdate));
$to_date = date('Y-m-d', strtotime($todate));

$result = $objLab->getLabServedServicesNscm($from_date,$to_date,$charge_type);
if($result) {
	if($result->RecordCount() > 0) {
		$i = 0;
		while ($row = $result->FetchRow()) {
			$date = date('m/d/Y', strtotime($row['serv_dt']));
			$time = date('h:i:A', strtotime($row['serv_tm']));
			$request_date_time = $date . " " . $time;
			$hrn = $row['pid'];
			if ($row['encounter_nr'] == '') {
				$encounter_nr = 'WALK-IN';
			} else {
				$encounter_nr = $row['encounter_nr'];
			}
			$patient_name = strtoupper($row['patient_name']);
			$refno = $row['refno'];
			$request_items = strtoupper($row['request_items']);
			$price = $row['price'];
			if(!empty($row['encoder'])){
				$encoder = strtoupper($row['encoder']);
			}
			else{
				$encoder = strtoupper($row['encoder_spl']);
			}
			// $encoder = strtoupper($row['encoder']);

			$total += $price;

			$data[$i] = array(
				'request_date_time' => $request_date_time,
				'hrn' => $hrn,
				'encounter_nr' => $encounter_nr,
				'patient_name' => $patient_name,
				'refno' => $refno,
				'request_items' => $request_items,
				'price' => $price,
				'encoder' => $encoder,
				'total' => number_format($total, 2, '.', '')
			);
			$i++;
		}
	}
	else{
		$data = array(
			array(
				'request_date_time' => 'No Results Found'
			)
		);
	}
}
else{
	$data = array(
		array(
			'request_date_time' => 'No Results Found'
		)
	);
}


showReport('LAB_Services_Charge_NSCM', $params, $data, 'PDF');
?>